name: example_non_ns
description: example_non_ns
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  built_value: ^7.1.0
  freezed_annotation: ^0.12.0

  flutter:
    sdk: flutter

  provider: ^5.0.0

dev_dependencies:
  build_runner: ^1.12.2
  built_value_generator: ^7.1.0
  freezed: ^0.12.0

  flutter_test:
    sdk: flutter

dependency_overrides:
  analyzer: ^1.0.0
  build: ^2.0.0
  json_annotation: ^4.0.0

flutter:
  uses-material-design: true
