name: example_with_ns
description: example_with_ns
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  built_value: ^8.0.0
  freezed_annotation: ^0.14.0

  flutter:
    sdk: flutter

  packet_a:
    path: ../packet_a
  packet_b:
    path: ../packet_b

  provider: ^5.0.0

  rxdart: ^0.26.0

dev_dependencies:
  build_runner: ^1.12.2
  built_value_generator: ^8.0.0
  freezed: ^0.14.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
