name: packet_b
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  packet_c:
    path: ../packet_c

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
